import type { WorkflowDefinition } from '@/domain/workflows';

export const customEnquiryWorkflow = {
  id: 'custom-enquiry',
  type: 'custom-enquiry',
  name: 'Custom enquiry',
  description: 'Starts a low-friction consultation for Events & Catering.',
  optionGroups: [
    {
      id: 'customer-name',
      kind: 'text',
      label: 'Name',
      required: true,
      displayOrder: 10,
      multiline: false,
      maxLength: 100,
      trim: true,
    },
    {
      id: 'customer-email',
      kind: 'text',
      label: 'Email',
      required: true,
      displayOrder: 20,
      multiline: false,
      maxLength: 254,
      trim: true,
    },
    {
      id: 'customer-phone',
      kind: 'text',
      label: 'Phone Number',
      required: true,
      displayOrder: 30,
      multiline: false,
      maxLength: 30,
      trim: true,
    },
    {
      id: 'event-type',
      kind: 'text',
      label: 'Event Type',
      required: true,
      displayOrder: 40,
      multiline: false,
      maxLength: 100,
      trim: true,
    },
    {
      id: 'message',
      kind: 'text',
      label: 'Message',
      description:
        'Briefly describe your event, initial ideas and anything important.',
      required: true,
      displayOrder: 50,
      multiline: true,
      maxLength: 1000,
      trim: true,
    },
    {
      id: 'preferred-event-date',
      kind: 'date',
      label: 'Preferred Event Date',
      required: false,
      displayOrder: 60,
    },
  ],
} as const satisfies WorkflowDefinition;
